<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQNyxOiX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQNyxOiX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQNyxOiX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQNyxOiX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQNyxOiX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QNyxOiX',
    'container.build_id' => '137a3534',
    'container.build_time' => 1627998765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQNyxOiX');
