<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\HomeController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/delete']], [], []],
    'update' => [['id'], ['_controller' => 'App\\Controller\\HomeController::update'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/update']], [], []],
];
